sonar.projectKey=andsantosx_integration-tests-anderson
sonar.organization=andsantosx
sonar.projectName=Integration Tests Anderson
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/*