sonar.projectKey=andsantosx_unit-tests-jest
sonar.organization=andsantosx
sonar.projectName=Unit Tests Jest
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/*
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2699
sonar.issue.ignore.multicriteria.e1.resourceKey=test/**/*.spec.ts